//! Static catalog of MSTS `.eng` / `.wag` tokens for cross-reference audits.
//!
//! Sources: openrailsrs typed parsers, OpenBVE `VehicleParser.cs`, Open Rails
//! `EngineFile.cs` / `MSTSLocomotive.cs` (documented in `docs/FORMATS.md`).

/// Which vehicle files a catalog entry applies to.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VehicleKind {
    Engine,
    Wagon,
    Both,
}

/// Whether a parser consumes a token for simulation or presentation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ParserSupport {
    /// Fully mapped into openrailsrs train/sim types.
    Parsed,
    /// Token read but only partially used (defaults, subset of block).
    Partial,
    /// Known token intentionally skipped (visual/audio-only).
    Ignored,
    /// Not handled by this parser.
    NotImplemented,
    /// Does not apply to this parser (e.g. ORTS-only for OpenBVE).
    NotApplicable,
}

/// One row in the vehicle field catalog.
#[derive(Clone, Copy, Debug)]
pub struct VehicleFieldSpec {
    pub token: &'static str,
    pub aliases: &'static [&'static str],
    pub applies_to: VehicleKind,
    pub openrailsrs: ParserSupport,
    pub openbve: ParserSupport,
    pub category: &'static str,
    pub notes: &'static str,
}

/// Master catalog (sorted by token for binary search).
pub static VEHICLE_FIELD_CATALOG: &[VehicleFieldSpec] = &[
    // ── Identity / shape ───────────────────────────────────────────────────
    field(
        "Engine",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "structure",
        "Root block",
    ),
    field(
        "Wagon",
        &[],
        VehicleKind::Wagon,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "structure",
        "Root block",
    ),
    field(
        "Name",
        &["Type"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::Partial,
        "identity",
        "Display name",
    ),
    field(
        "WagonShape",
        &["Shape"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "visual",
        "Exterior .s path",
    ),
    field(
        "Size",
        &[],
        VehicleKind::Both,
        ParserSupport::Partial,
        ParserSupport::Parsed,
        "visual",
        "openrailsrs uses length component only",
    ),
    field(
        "Length",
        &["ORTSLengthCarBody", "ORTSLengthCouplerFace", "WagonLength"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::Partial,
        "visual",
        "",
    ),
    field(
        "Mass",
        &["MassKG"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    // ── Tractive / diesel (MSTS core) ──────────────────────────────────────
    field(
        "MaxPower",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "MaxForce",
        &["MaxTractiveEffort"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "OpenBVE maps to simplified acceleration curve",
    ),
    field(
        "MaxContinuousForce",
        &["MaxContinuousTractiveForce"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "MaxVelocity",
        &["MaxSpeed"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "RunUpTimeToMaxForce",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "Legacy MSTS ramp",
    ),
    field(
        "WheelRadius",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "Gap: OpenBVE uses for axle model",
    ),
    field(
        "NumWheels",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "DieselEngineIdleRPM",
        &["IdleRPM"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "Also under ORTSDieselEngines",
    ),
    field(
        "DieselEngineMaxRPM",
        &["MaxRPM"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "DieselEngineMaxRPMChangeRate",
        &[
            "ChangeUpRPMpS",
            "ChangeDownRPMpS",
            "RateOfChangeUpRPMpSS",
            "RateOfChangeDownRPMpSS",
        ],
        VehicleKind::Engine,
        ParserSupport::Partial,
        ParserSupport::Parsed,
        "physics",
        "openrailsrs reads ORTS RateOfChange* inside ORTSDieselEngines",
    ),
    field(
        "DieselUsedPerHourAtIdle",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "Fuel model gap",
    ),
    field(
        "DieselUsedPerHourAtMaxPower",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "MaxDieselLevel",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "DieselPowerTab",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "ORTS/MSTS tab; OpenBVE uses MaxForce curve",
    ),
    field(
        "ThrottleRPMTab",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "OR parity diesel",
    ),
    field(
        "ReverseThrottleRPMTab",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "Apparent throttle (OR-P1)",
    ),
    field(
        "ORTSDieselEngines",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "OR extension block",
    ),
    field(
        "ORTSMaxTractiveForceCurves",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "Per-notch tractive curves",
    ),
    field(
        "ORTSMaxRailOutputPowerW",
        &["LocomotiveMaxRailOutputPowerW", "MaxRailOutputPowerW"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSUnloadingSpeed",
        &["UnloadingSpeed"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSTractiveForceIsPowerLimited",
        &["TractiveForceIsPowerLimited"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "SpeedOfMaxContinuousForce",
        &["ORTSSpeedOfMaxContinuousForce"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "",
    ),
    field(
        "RegenFactor",
        &["RegenBraking"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "",
    ),
    field(
        "SpecificFuelConsumption",
        &["DieselSfc"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "physics",
        "",
    ),
    // ── Davis / friction / adhesion ──────────────────────────────────────────
    field(
        "ORTSDavis_A",
        &[],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSDavis_B",
        &[],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSDavis_C",
        &[],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSFriction",
        &["ORTSWagonFriction", "ORTSLocomotiveFriction"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "Friction",
        &[],
        VehicleKind::Both,
        ParserSupport::Partial,
        ParserSupport::Parsed,
        "physics",
        "MSTS block → openrailsrs friction adapter",
    ),
    field(
        "Adheasion",
        &["Adhesion", "ORTSAdhesion"],
        VehicleKind::Engine,
        ParserSupport::Partial,
        ParserSupport::Parsed,
        "physics",
        "MSTS typo preserved in files",
    ),
    field(
        "ORTSDriveWheelWeight",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "Curtius-Kniffler input",
    ),
    field(
        "ORTSCurtius_Kniffler",
        &[],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "AntiSlip",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    // ── Brakes ───────────────────────────────────────────────────────────────
    field(
        "MaxBrakeForce",
        &["ORTSMaxBrakeShoeForce", "MaxBrakeShoeForce", "Brake"],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "brake",
        "",
    ),
    field(
        "BrakeSystemType",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "MSTS air/vacuum type → OpenBVE brake model",
    ),
    field(
        "BrakeEquipmentType",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "",
    ),
    field(
        "AirBrakesMainMaxAirPressure",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "Pneumatic reservoir",
    ),
    field(
        "AirBrakesMainMinResAirPressure",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "",
    ),
    field(
        "BrakeCylinderPressureForMaxBrakeBrakeForce",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "",
    ),
    field(
        "TrainBrakesControllerMaxReleaseRate",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "brake",
        "",
    ),
    field(
        "ORTSBrakeShoeType",
        &[],
        VehicleKind::Both,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "brake",
        "",
    ),
    // ── Cab / sound / FX ─────────────────────────────────────────────────────
    field(
        "CabView",
        &["ORTS3DCab", "ORTS3DCabFile"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::Parsed,
        "cab",
        "Linked to CVF via cab_link::resolve_cab_assets",
    ),
    field(
        "ORTS3DCabHeadPos",
        &[
            "StartDirection",
            "RotationLimit",
            "ORTSAlternate3DCabViewPoints",
            "ORTSAlternate3DCabViewPoint",
            "HeadOut",
        ],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "cab",
        "EngineCabView viewpoints; used by viewer3d cab camera",
    ),
    field(
        "Sound",
        &["ORTSSoundFileName"],
        VehicleKind::Both,
        ParserSupport::Ignored,
        ParserSupport::Parsed,
        "audio",
        ".sms reference",
    ),
    field(
        "EngineControllers",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "cab",
        "Notch definitions",
    ),
    field(
        "Throttle",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "cab",
        "",
    ),
    field(
        "Brake_Train",
        &["TrainBrakesController"],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "cab",
        "",
    ),
    field(
        "Brake_Engine",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "cab",
        "",
    ),
    field(
        "AWSMonitor",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Partial,
        "safety",
        "",
    ),
    field(
        "OverspeedMonitor",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Partial,
        "safety",
        "",
    ),
    field(
        "VigilanceMonitor",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Partial,
        "safety",
        "",
    ),
    // ── Gearbox / steam (selected) ───────────────────────────────────────────
    field(
        "GearBoxNumberOfGears",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "OR-P9 gap",
    ),
    field(
        "GearBoxMaxSpeedForGears",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "GearBoxMaxTractiveForceForGears",
        &[],
        VehicleKind::Engine,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "physics",
        "",
    ),
    field(
        "NumCylinders",
        &["ORTSNumCylinder"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "steam",
        "",
    ),
    field(
        "CylinderDiameter",
        &["ORTSCylinderDiameter"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotImplemented,
        "steam",
        "",
    ),
    field(
        "MaxBoilerOutput",
        &[],
        VehicleKind::Engine,
        ParserSupport::Partial,
        ParserSupport::Partial,
        "steam",
        "OpenBVE steam WIP",
    ),
    field(
        "Coupling",
        &[],
        VehicleKind::Both,
        ParserSupport::NotImplemented,
        ParserSupport::Parsed,
        "coupling",
        "",
    ),
    field(
        "FreightAnim",
        &["ORTSFreightAnims"],
        VehicleKind::Both,
        ParserSupport::Ignored,
        ParserSupport::Parsed,
        "visual",
        "",
    ),
    field(
        "Effects",
        &["SteamSpecialEffects", "DieselSpecialEffects"],
        VehicleKind::Engine,
        ParserSupport::Ignored,
        ParserSupport::Parsed,
        "visual",
        "Particle FX",
    ),
    // ── ORTS ramps / heating (openrailsrs-only today) ────────────────────────
    field(
        "ORTSTractiveForceRampUpRate",
        &["TractiveForceRampUpRate"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSTractiveForceRampDownRate",
        &["TractiveForceRampDownRate"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "ORTSContinuousForceTimeFactor",
        &["ContinuousForceTimeFactor"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
    field(
        "TractiveForceAvgUsageTimeFactor",
        &["ORTSTractiveForceAvgUsageTimeFactor"],
        VehicleKind::Engine,
        ParserSupport::Parsed,
        ParserSupport::NotApplicable,
        "physics",
        "",
    ),
];

const fn field(
    token: &'static str,
    aliases: &'static [&'static str],
    applies_to: VehicleKind,
    openrailsrs: ParserSupport,
    openbve: ParserSupport,
    category: &'static str,
    notes: &'static str,
) -> VehicleFieldSpec {
    VehicleFieldSpec {
        token,
        aliases,
        applies_to,
        openrailsrs,
        openbve,
        category,
        notes,
    }
}

/// Lookup catalog entry by token (case-insensitive), including aliases.
pub fn lookup_field(token: &str) -> Option<&'static VehicleFieldSpec> {
    let upper = token.to_ascii_uppercase();
    VEHICLE_FIELD_CATALOG.iter().find(|spec| {
        spec.token.eq_ignore_ascii_case(token)
            || spec.aliases.iter().any(|a| a.eq_ignore_ascii_case(token))
            || spec.token.to_ascii_uppercase() == upper
    })
}

/// All catalog entries applicable to the given vehicle kind.
pub fn catalog_for_kind(kind: VehicleKind) -> impl Iterator<Item = &'static VehicleFieldSpec> {
    VEHICLE_FIELD_CATALOG.iter().filter(move |spec| {
        spec.applies_to == VehicleKind::Both || spec.applies_to == kind || kind == VehicleKind::Both
    })
}
