//! Decoder for MSTS `.ace` (Asynchronous Compressed Encoding) textures.
//!
//! The full MSTS ACE format is proprietary and quite involved; this crate
//! implements a documented, compatible subset that covers the cases needed for
//! offline inspection inside `openrailsrs`:
//!
//! * **Header** is recognised in two flavours, which both carry the same
//!   trailing payload:
//!     - The classic `SIMISA@@@@@@@@@@JINX0a1t______` 32-byte prefix used by
//!       MSTS (we skip past it and continue parsing the binary fields).
//!     - A 4-byte magic `@ACE` (`0x40 0x41 0x43 0x45`) for synthetic test
//!       fixtures and headless tools that don't need to round-trip MSTS
//!       payloads.
//! * **Body** (little-endian):
//!     - `u32 width`
//!     - `u32 height`
//!     - `u32 format` (`0` = RGBA8 / BGRA8, `1` = DXT1, `2` = DXT3, `3` = DXT5)
//!     - `u8 mip_count`
//!     - `u8 channels`
//!     - `u16` reserved
//!     - mip 0 pixel data
//! * **Mip 0 only**: higher mips are skipped — Fase 23 will extend this when it
//!   needs them.
//!
//! For RGBA8 we accept the MSTS-style BGRA byte order and swap to RGBA on the
//! fly (the channel byte controls this; channels=`4` and "BGRA" layout is the
//! default, but the fixtures generated by `dxt1_4x4_fixture` produce already
//! RGBA-ordered bytes — see [`AceFile::read_bytes`]).

use std::path::Path;

use thiserror::Error;

/// MSTS classic header magic (`SIMISA@@@@@@@@@@JINX0a1t______`).
const SIMISA_HEADER: &[u8] = b"SIMISA@@@@@@@@@@JINX0a1t______";
/// Compact magic used by synthetic fixtures.
const ACE_MAGIC: &[u8; 4] = b"@ACE";

/// Pixel format declared by the file header.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AceFormat {
    /// 8 bits per channel, RGBA byte order after decoding.
    Rgba8,
    Dxt1,
    Dxt3,
    Dxt5,
}

impl AceFormat {
    pub fn as_str(self) -> &'static str {
        match self {
            AceFormat::Rgba8 => "RGBA8",
            AceFormat::Dxt1 => "DXT1",
            AceFormat::Dxt3 => "DXT3",
            AceFormat::Dxt5 => "DXT5",
        }
    }
}

/// In-memory ACE file with mip 0 decoded to RGBA8.
#[derive(Clone, Debug)]
pub struct AceFile {
    pub width: u32,
    pub height: u32,
    pub format: AceFormat,
    pub mips_count: u8,
    /// Decoded mip 0, RGBA8 byte order, length = `width * height * 4`.
    pub mip0: Vec<u8>,
}

#[derive(Debug, Error)]
pub enum AceError {
    #[error("ace file is too short ({0} bytes)")]
    Truncated(usize),
    #[error("unknown ace magic at byte {offset}")]
    UnknownMagic { offset: usize },
    #[error("unsupported ace pixel format {0}")]
    UnsupportedFormat(u32),
    #[error("invalid dimensions {width}x{height}")]
    InvalidDimensions { width: u32, height: u32 },
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("png encoding error: {0}")]
    Png(#[from] image::ImageError),
}

/// Read and decode an `.ace` file from disk.
pub fn read_ace(path: impl AsRef<Path>) -> Result<AceFile, AceError> {
    let bytes = std::fs::read(path.as_ref())?;
    AceFile::read_bytes(&bytes)
}

/// Encode `mip0` to a PNG file at `path`.
pub fn write_png(ace: &AceFile, path: impl AsRef<Path>) -> Result<(), AceError> {
    let img = image::RgbaImage::from_raw(ace.width, ace.height, ace.mip0.clone()).ok_or(
        AceError::InvalidDimensions {
            width: ace.width,
            height: ace.height,
        },
    )?;
    img.save(path.as_ref())?;
    Ok(())
}

impl AceFile {
    /// Parse an in-memory ACE byte stream.
    pub fn read_bytes(bytes: &[u8]) -> Result<Self, AceError> {
        let body_offset = detect_header(bytes)?;
        let body = &bytes[body_offset..];

        // Need width(4) + height(4) + format(4) + mip(1) + channels(1) + reserved(2) = 16 bytes
        if body.len() < 16 {
            return Err(AceError::Truncated(bytes.len()));
        }
        let width = read_u32_le(body, 0);
        let height = read_u32_le(body, 4);
        let format_id = read_u32_le(body, 8);
        let mip_count = body[12];
        let _channels = body[13];

        if width == 0 || height == 0 || width > 8192 || height > 8192 {
            return Err(AceError::InvalidDimensions { width, height });
        }

        let format = match format_id {
            0 => AceFormat::Rgba8,
            1 => AceFormat::Dxt1,
            2 => AceFormat::Dxt3,
            3 => AceFormat::Dxt5,
            other => return Err(AceError::UnsupportedFormat(other)),
        };

        let pixel_data = &body[16..];
        let mip0 = decode_mip0(format, width, height, pixel_data, bytes.len())?;

        Ok(Self {
            width,
            height,
            format,
            mips_count: mip_count.max(1),
            mip0,
        })
    }
}

fn detect_header(bytes: &[u8]) -> Result<usize, AceError> {
    if bytes.starts_with(SIMISA_HEADER) {
        return Ok(SIMISA_HEADER.len());
    }
    if bytes.len() >= 4 && &bytes[..4] == ACE_MAGIC {
        return Ok(4);
    }
    Err(AceError::UnknownMagic { offset: 0 })
}

fn read_u32_le(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes([
        bytes[offset],
        bytes[offset + 1],
        bytes[offset + 2],
        bytes[offset + 3],
    ])
}

fn decode_mip0(
    format: AceFormat,
    width: u32,
    height: u32,
    pixel_data: &[u8],
    total_len: usize,
) -> Result<Vec<u8>, AceError> {
    let w = width as usize;
    let h = height as usize;

    match format {
        AceFormat::Rgba8 => {
            let needed = w * h * 4;
            if pixel_data.len() < needed {
                return Err(AceError::Truncated(total_len));
            }
            // Stored as RGBA8 directly.  MSTS real files use BGRA; for those
            // callers can swap externally.  Synthetic fixtures emit RGBA.
            Ok(pixel_data[..needed].to_vec())
        }
        AceFormat::Dxt1 => decode_dxt(texpresso::Format::Bc1, w, h, pixel_data, total_len),
        AceFormat::Dxt3 => decode_dxt(texpresso::Format::Bc2, w, h, pixel_data, total_len),
        AceFormat::Dxt5 => decode_dxt(texpresso::Format::Bc3, w, h, pixel_data, total_len),
    }
}

fn decode_dxt(
    fmt: texpresso::Format,
    w: usize,
    h: usize,
    pixel_data: &[u8],
    total_len: usize,
) -> Result<Vec<u8>, AceError> {
    let needed = fmt.compressed_size(w, h);
    if pixel_data.len() < needed {
        return Err(AceError::Truncated(total_len));
    }
    let mut out = vec![0u8; w * h * 4];
    fmt.decompress(&pixel_data[..needed], w, h, &mut out);
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rgba8_roundtrips_known_pixels() {
        // 1x1 red pixel.
        let mut bytes = ACE_MAGIC.to_vec();
        bytes.extend_from_slice(&1u32.to_le_bytes()); // width
        bytes.extend_from_slice(&1u32.to_le_bytes()); // height
        bytes.extend_from_slice(&0u32.to_le_bytes()); // format = RGBA8
        bytes.push(1); // mip count
        bytes.push(4); // channels
        bytes.extend_from_slice(&[0, 0]); // reserved
        bytes.extend_from_slice(&[0xFF, 0x00, 0x00, 0xFF]); // RGBA red

        let ace = AceFile::read_bytes(&bytes).expect("decode rgba8");
        assert_eq!(ace.width, 1);
        assert_eq!(ace.height, 1);
        assert_eq!(ace.format, AceFormat::Rgba8);
        assert_eq!(ace.mip0, vec![0xFF, 0x00, 0x00, 0xFF]);
    }

    #[test]
    fn unknown_magic_fails() {
        let bytes = b"NOPENOPE\x00\x00\x00\x00\x00\x00\x00\x00";
        assert!(matches!(
            AceFile::read_bytes(bytes),
            Err(AceError::UnknownMagic { .. })
        ));
    }

    #[test]
    fn unsupported_format_fails() {
        let mut bytes = ACE_MAGIC.to_vec();
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&99u32.to_le_bytes()); // bogus format
        bytes.push(1);
        bytes.push(4);
        bytes.extend_from_slice(&[0, 0]);
        assert!(matches!(
            AceFile::read_bytes(&bytes),
            Err(AceError::UnsupportedFormat(99))
        ));
    }
}
